if(MIDILAR_DSP_LUT1D)
    message(STATUS "MIDILAR::dspFoundation::LUT1D")
    target_compile_definitions(MIDILAR PUBLIC MIDILAR_LUT1D)
    list(APPEND ${PROJECT_NAME_UPPER}_MACROS "MIDILAR_LUT1D")
endif()

if(MIDILAR_DSP_LUT2D)
    message(STATUS "MIDILAR::dspFoundation::LUT2D")
    target_compile_definitions(MIDILAR PUBLIC MIDILAR_LUT2D)
    list(APPEND ${PROJECT_NAME_UPPER}_MACROS "MIDILAR_LUT2D")
endif()

if(MIDILAR_DSP_LUT3D)
    message(STATUS "MIDILAR::dspFoundation::LUT3D")
    target_compile_definitions(MIDILAR PUBLIC MIDILAR_LUT3D)
    list(APPEND ${PROJECT_NAME_UPPER}_MACROS "MIDILAR_LUT3D")
endif()

if(MIDILAR_DSP_LUT_PERIODIC)
    message(STATUS "MIDILAR::dspFoundation::LUTPeriodic")
    target_compile_definitions(MIDILAR PUBLIC MIDILAR_LUT_PERIODIC)
    list(APPEND ${PROJECT_NAME_UPPER}_MACROS "MIDILAR_LUT_PERIODIC")
endif()

if(MIDILAR_DSP_LUT_SHAPING)
    message(STATUS "MIDILAR::dspFoundation::LUTShaping")
    target_compile_definitions(MIDILAR PUBLIC MIDILAR_LUT_SHAPING)
    list(APPEND ${PROJECT_NAME_UPPER}_MACROS "MIDILAR_LUT_SHAPING")
endif()