#ifndef MIDILAR_DEPENDENCY_RESOLUTION_H
#define MIDILAR_DEPENDENCY_RESOLUTION_H

    #if defined(MIDILAR_GENERATORS_ENVELOPES) || defined(MIDILAR_GENERATORS_PERIODIC) || defined(MIDILAR_GENERATORS_SHAPING)  || defined(MIDILAR_GENERATORS_WINDOWING)
        #define MIDILAR_DSP_FOUNDATION
        #define MIDILAR_GENERATORS
    #endif
    
    #if defined(MIDILAR_GENERATORS) 
        #define MIDILAR_DSP_FOUNDATION
    #endif
    
    #if defined(MIDILAR_INTERPOLATORS) 
        #define MIDILAR_DSP_FOUNDATION
    #endif

    #if defined(MIDILAR_LUT_PERIODIC_SINE) || defined(MIDILAR_LUT_PERIODIC_TRIANGLE) || defined(MIDILAR_LUT_PERIODIC_SAW)  || defined(MIDILAR_LUT_PERIODIC_SQUARE)
        #define MIDILAR_LUT_PERIODIC
        #define MIDILAR_LUT
        #define MIDILAR_DSP_FOUNDATION
    #endif


#endif // MIDILAR_DEPENDENCY_RESOLUTION_H
