

# ========== System Foundation ==========
set(MIDILAR_SYSTEM_FOUNDATION_DEPS "MIDILAR_SYSTEM_FOUNDATION" CACHE INTERNAL "")
    
    # ========== Clock ==========
    set(MIDILAR_SYSTEM_CLOCK_DEPS "${MIDILAR_SYSTEM_FOUNDATION_DEPS};MIDILAR_SYSTEM_CLOCK" CACHE INTERNAL "")

    # ========== Callback Handler ==========
    set(MIDILAR_CALLBACK_HANDLER_DEPS "${MIDILAR_SYSTEM_FOUNDATION_DEPS};MIDILAR_CALLBACK_HANDLER" CACHE INTERNAL "")

# ========== MIDI Foundation ==========
set(MIDILAR_MIDI_FOUNDATION_DEPS "MIDILAR_MIDI_FOUNDATION" CACHE INTERNAL "")
    
    # ========== Protocol Enums ==========
    set(MIDILAR_PROTOCOL_ENUMS_DEPS "${MIDILAR_MIDI_FOUNDATION_DEPS};MIDILAR_PROTOCOL_ENUMS" CACHE INTERNAL "")

    # ========== MIDI Message ==========
    set(MIDILAR_MIDI_MESSAGE_DEPS "${MIDILAR_MIDI_FOUNDATION_DEPS};MIDILAR_MIDI_MESSAGE" CACHE INTERNAL "")

    # ========== MIDI Message Parser ==========
    set(MIDILAR_MIDI_MESSAGE_PARSER_DEPS "${MIDILAR_MIDI_FOUNDATION_DEPS};MIDILAR_MIDI_MESSAGE_PARSER" CACHE INTERNAL "")

    # ========== MIDI Message Processor ==========
    set(MIDILAR_MIDI_PROCESSOR_DEPS "${MIDILAR_MIDI_FOUNDATION_DEPS};MIDILAR_MIDI_PROCESSOR" CACHE INTERNAL "")

# ========== DSP Foundation ==========
set(MIDILAR_DSP_FOUNDATION_DEPS "MIDILAR_DSP_FOUNDATION" CACHE INTERNAL "")

    # ========== LUT ==========
    set(MIDILAR_LUT_DEPS "${MIDILAR_DSP_FOUNDATION_DEPS};MIDILAR_LUT" CACHE INTERNAL "")
    set(MIDILAR_LUT1D_DEPS "${MIDILAR_LUT_DEPS};MIDILAR_LUT1D" CACHE INTERNAL "")
    set(MIDILAR_LUT2D_DEPS "${MIDILAR_LUT_DEPS};MIDILAR_LUT2D" CACHE INTERNAL "")
    set(MIDILAR_LUT3D_DEPS "${MIDILAR_LUT_DEPS};MIDILAR_LUT3D" CACHE INTERNAL "")

        # ========== Periodic ==========
        set(MIDILAR_LUT_PERIODIC_DEPS "${MIDILAR_LUT_DEPS};MIDILAR_LUT_PERIODIC" CACHE INTERNAL "")
        set(MIDILAR_LUT_PERIODIC_SINE_DEPS "${MIDILAR_LUT1D_DEPS};MIDILAR_LUT_PERIODIC_SINE" CACHE INTERNAL "")
        set(MIDILAR_LUT_PERIODIC_TRIANGLE_DEPS "${MIDILAR_LUT1D_DEPS};MIDILAR_LUT_PERIODIC_TRIANGLE" CACHE INTERNAL "")
        set(MIDILAR_LUT_PERIODIC_SQUARE_DEPS "${MIDILAR_LUT1D_DEPS};MIDILAR_LUT_PERIODIC_SQUARE" CACHE INTERNAL "")
        set(MIDILAR_LUT_PERIODIC_SAW_DEPS "${MIDILAR_LUT1D_DEPS};MIDILAR_LUT_PERIODIC_SAW" CACHE INTERNAL "")

        # ========== Shaping ==========
        set(MIDILAR_LUT_SHAPING_DEPS "${MIDILAR_LUT_DEPS};MIDILAR_LUT_SHAPING" CACHE INTERNAL "")
        set(MIDILAR_GAMMA_LUT_DEPS "${MIDILAR_LUT_SHAPING_DEPS};${MIDILAR_LUT3D_DEPS};MIDILAR_GAMMA_LUT" CACHE INTERNAL "")

    # ========== STREAMING ==========
    set(MIDILAR_STREAMING_DEPS "${MIDILAR_DSP_FOUNDATION_DEPS};MIDILAR_STREAMING" CACHE INTERNAL "")
    set(MIDILAR_STREAMING_LOGIC_DEPS "${MIDILAR_STREAMING_DEPS};MIDILAR_STREAMING_LOGIC" CACHE INTERNAL "")
    set(MIDILAR_LEVEL_TRANSITION_TRACKER_DEPS "${MIDILAR_STREAMING_LOGIC_DEPS};MIDILAR_LEVEL_TRANSITION_TRACKER" CACHE INTERNAL "")
    set(MIDILAR_STREAMING_EDGE_DETECTOR_DEPS "${MIDILAR_LEVEL_TRANSITION_TRACKER_DEPS};MIDILAR_STREAMING_EDGE_DETECTOR" CACHE INTERNAL "")
    set(MIDILAR_STREAMING_SCHMITT_TRIGGER_DEPS "${MIDILAR_LEVEL_TRANSITION_TRACKER_DEPS};MIDILAR_STREAMING_SCHMITT_TRIGGER" CACHE INTERNAL "")

# ========== MIDI Devices ==========
set(MIDILAR_MIDI_DEVICES_DEPS "${MIDILAR_MIDI_PROCESSOR_DEPS};MIDILAR_MIDI_DEVICES" CACHE INTERNAL "")
    
    # ========== Channel Reassign ==========
    set(MIDILAR_CHANNEL_REASSIGN_DEPS "${MIDILAR_MIDI_DEVICES_DEPS};MIDILAR_CHANNEL_REASSIGN" CACHE INTERNAL "")

    # ========== Velocity Shaper ==========
    set(MIDILAR_VELOCITY_SHAPER_DEPS "${MIDILAR_MIDI_DEVICES_DEPS};MIDILAR_VELOCITY_SHAPER" CACHE INTERNAL "")
