#ifndef MIDILAR_USER_SETUP_H
#define MIDILAR_USER_SETUP_H

	#define MIDILAR_SYSTEM_FOUNDATION

		#define MIDILAR_CALLBACK_HANDLER
		#define MIDILAR_SYSTEM_CLOCK

	#define MIDILAR_MIDI_FOUNDATION

		#define MIDILAR_PROTOCOL_ENUMS
		#define MIDILAR_MIDI_MESSAGE
		#define MIDILAR_MIDI_MESSAGE_PARSER
		#define MIDILAR_MIDI_PROCESSOR

	#define MIDILAR_AUDIO_FOUNDATION

		#define MIDILAR_LUT

	#define MIDILAR_MIDI_PROCESORS


#endif//MIDILAR_USER_SETUP_H