#ifndef MIDILAR_USER_SETUP_H
#define MIDILAR_USER_SETUP_H

	#define MIDILAR_SYSTEM_FOUNDATION

		#define MIDILAR_SYSTEM_CALLBACK_HANDLER
		#define MIDILAR_SYSTEM_CLOCK

	#define MIDILAR_DSP_FOUNDATION

		#define MIDILAR_LUT
			#define MIDILAR_LUT1D
			#define MIDILAR_LUT2D
			#define MIDILAR_LUT3D

			#define MIDILAR_LUT_PERIODIC
				#define MIDILAR_LUT_PERIODIC_SINE
				#define MIDILAR_LUT_PERIODIC_TRIANGLE
				#define MIDILAR_LUT_PERIODIC_SAW
				#define MIDILAR_LUT_PERIODIC_SQUARE

			#define MIDILAR_LUT_SHAPING
				#define MIDILAR_GAMMA_LUT
			
		#define MIDILAR_GENERATORS
			#define MIDILAR_GENERATORS_PERIODIC
			#define MIDILAR_GENERATORS_SHAPING
			#define MIDILAR_GENERATORS_WINDOWING
			#define MIDILAR_GENERATORS_ENVELOPES
			
		#define MIDILAR_STREAMING
			#define MIDILAR_STREAMING_LOGIC
				#define MIDILAR_LEVEL_TRANSITION_TRACKER
					#define MIDILAR_STREAMING_EDGE_DETECTOR
					#define MIDILAR_STREAMING_SCHMITT_TRIGGER
					
				#define MIDILAR_STATE_CHANGE_GATE

		#define MIDILAR_TRANSFORMS
			#define MIDILAR_TRANSFORMS_DFT

	#define MIDILAR_MIDI_FOUNDATION

		#define MIDILAR_PROTOCOL_ENUMS
		#define MIDILAR_MIDI_MESSAGE
		#define MIDILAR_MIDI_MESSAGE_PARSER
		#define MIDILAR_MIDI_PROCESSOR

	#define MIDILAR_MIDI_DEVICES

#endif//MIDILAR_USER_SETUP_H