set(MIDILAR_CORE_HEADERS
    "${CMAKE_CURRENT_LIST_DIR}/Version.h")
set(MIDILAR_CORE_SOURCES
    "${CMAKE_CURRENT_LIST_DIR}/Version.cpp")

target_sources(MIDILAR PRIVATE ${MIDILAR_CORE_HEADERS} ${MIDILAR_CORE_SOURCES})
midilar_stage_headers(${MIDILAR_CORE_HEADERS})
midilar_add_dox(
    ${MIDILAR_CORE_HEADERS}
    "${CMAKE_CURRENT_LIST_DIR}/Core.dox")

install(FILES ${MIDILAR_CORE_HEADERS}
    DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/MIDILAR/Core"
    CONFIGURATIONS Release)
