if(MIDILAR_DSP_GENERATORS)
    message(STATUS "MIDILAR::dspFoundation::Generators")
    target_compile_definitions(MIDILAR PUBLIC MIDILAR_DSP_GENERATORS)
    list(APPEND ${PROJECT_NAME_UPPER}_MACROS "MIDILAR_DSP_GENERATORS")
    include(${CMAKE_CURRENT_LIST_DIR}/Generators/CMakeMacros.cmake)
endif()

if(MIDILAR_DSP_LUT)
    message(STATUS "MIDILAR::dspFoundation::LUT")
    target_compile_definitions(MIDILAR PUBLIC MIDILAR_DSP_LUT)
    list(APPEND ${PROJECT_NAME_UPPER}_MACROS "MIDILAR_DSP_LUT")
    include(${CMAKE_CURRENT_LIST_DIR}/LUT/CMakeMacros.cmake)
endif()

if(MIDILAR_DSP_INTERPOLATORS)
    message(STATUS "MIDILAR::dspFoundation::Interpolators")
    target_compile_definitions(MIDILAR PUBLIC MIDILAR_DSP_INTERPOLATORS)
    list(APPEND ${PROJECT_NAME_UPPER}_MACROS "MIDILAR_DSP_INTERPOLATORS")
    include(${CMAKE_CURRENT_LIST_DIR}/Interpolators/CMakeMacros.cmake)
endif()
