if(MIDILAR_GENERATORS_ENVELOPES)
    message(STATUS "MIDILAR::dspFoundation::Generators::Envelopes")
    target_compile_definitions(MIDILAR PUBLIC MIDILAR_GENERATORS_ENVELOPES)
    list(APPEND ${PROJECT_NAME_UPPER}_MACROS "MIDILAR_GENERATORS_ENVELOPES")
    include(${CMAKE_CURRENT_LIST_DIR}/Envelopes/CMakeMacros.cmake)
endif()

if(MIDILAR_GENERATORS_NOISE)
    message(STATUS "MIDILAR::dspFoundation::Generators::Noise")
    target_compile_definitions(MIDILAR PUBLIC MIDILAR_GENERATORS_NOISE)
    list(APPEND ${PROJECT_NAME_UPPER}_MACROS "MIDILAR_GENERATORS_NOISE")
    include(${CMAKE_CURRENT_LIST_DIR}/Noise/CMakeMacros.cmake)
endif()

if(MIDILAR_GENERATORS_PERIODIC)
    message(STATUS "MIDILAR::dspFoundation::Generators::Periodic")
    target_compile_definitions(MIDILAR PUBLIC MIDILAR_GENERATORS_PERIODIC)
    list(APPEND ${PROJECT_NAME_UPPER}_MACROS "MIDILAR_GENERATORS_PERIODIC")
    include(${CMAKE_CURRENT_LIST_DIR}/Periodic/CMakeMacros.cmake)
endif()

if(MIDILAR_GENERATORS_SHAPING)
    message(STATUS "MIDILAR::dspFoundation::Generators::Shaping")
    target_compile_definitions(MIDILAR PUBLIC MIDILAR_GENERATORS_SHAPING)
    list(APPEND ${PROJECT_NAME_UPPER}_MACROS "MIDILAR_GENERATORS_SHAPING")
    include(${CMAKE_CURRENT_LIST_DIR}/Shaping/CMakeMacros.cmake)
endif()

if(MIDILAR_GENERATORS_WINDOWING)
    message(STATUS "MIDILAR::dspFoundation::Generators::Windowing")
    target_compile_definitions(MIDILAR PUBLIC MIDILAR_GENERATORS_WINDOWING)
    list(APPEND ${PROJECT_NAME_UPPER}_MACROS "MIDILAR_GENERATORS_WINDOWING")
    include(${CMAKE_CURRENT_LIST_DIR}/Windowing/CMakeMacros.cmake)
endif()
