#!/bin/sh

MIDILAR_SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
MIDILAR_ROOT=$(CDPATH= cd -- "$MIDILAR_SCRIPT_DIR/.." && pwd)
MIDILAR_BUILD_ROOT="$MIDILAR_ROOT/build"
MIDILAR_DIST_ROOT="$MIDILAR_ROOT/dist"
MIDILAR_ROMODULAR_SCRIPTS="$MIDILAR_ROOT/tools/RoModularBuild/scripts"

if [ ! -f "$MIDILAR_ROMODULAR_SCRIPTS/common.sh" ]; then
    printf '%s\n' \
        "error: RoModularBuild is unavailable; initialize tools/RoModularBuild with git submodule update --init --recursive" \
        >&2
    exit 2
fi

ROMODULAR_PROJECT_ROOT=$MIDILAR_ROOT
ROMODULAR_BUILD_ROOT=$MIDILAR_BUILD_ROOT
ROMODULAR_DIST_ROOT=$MIDILAR_DIST_ROOT
ROMODULAR_PROJECT_LABEL=MIDILAR
ROMODULAR_CONFIGURE_COMMAND=scripts/configure.sh
ROMODULAR_DEFAULT_CONFIGURATION=Debug
ROMODULAR_DOCUMENTATION_PRESET=documentation
ROMODULAR_DOCUMENTATION_CONFIGURATION=Release
ROMODULAR_INSTALL_CONFIGURATION=Release
ROMODULAR_TESTING_CACHE_ARGUMENT=-DMIDILAR_TESTING=ON
ROMODULAR_EXAMPLES_CACHE_ARGUMENT=-DMIDILAR_EXAMPLES=ON

export \
    ROMODULAR_PROJECT_ROOT \
    ROMODULAR_BUILD_ROOT \
    ROMODULAR_DIST_ROOT \
    ROMODULAR_PROJECT_LABEL \
    ROMODULAR_CONFIGURE_COMMAND \
    ROMODULAR_DEFAULT_CONFIGURATION \
    ROMODULAR_DOCUMENTATION_PRESET \
    ROMODULAR_DOCUMENTATION_CONFIGURATION \
    ROMODULAR_INSTALL_CONFIGURATION \
    ROMODULAR_TESTING_CACHE_ARGUMENT \
    ROMODULAR_EXAMPLES_CACHE_ARGUMENT
