set(MIDILAR_SRC_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}")

add_library(MIDILAR STATIC)
add_library(MIDILAR::MIDILAR ALIAS MIDILAR)

target_compile_features(MIDILAR PUBLIC cxx_std_${MIDILAR_REQUIRED_CXX_STANDARD})
target_link_libraries(MIDILAR PUBLIC Foundation::Foundation MCC::MCC)

set(MIDILAR_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/artifacts")
set_target_properties(MIDILAR PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY "${MIDILAR_OUTPUT_DIRECTORY}/lib"
    ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${MIDILAR_OUTPUT_DIRECTORY}/lib"
    ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${MIDILAR_OUTPUT_DIRECTORY}/lib"
    LIBRARY_OUTPUT_DIRECTORY "${MIDILAR_OUTPUT_DIRECTORY}/lib"
    LIBRARY_OUTPUT_DIRECTORY_DEBUG "${MIDILAR_OUTPUT_DIRECTORY}/lib"
    LIBRARY_OUTPUT_DIRECTORY_RELEASE "${MIDILAR_OUTPUT_DIRECTORY}/lib"
    RUNTIME_OUTPUT_DIRECTORY "${MIDILAR_OUTPUT_DIRECTORY}/bin"
    RUNTIME_OUTPUT_DIRECTORY_DEBUG "${MIDILAR_OUTPUT_DIRECTORY}/bin"
    RUNTIME_OUTPUT_DIRECTORY_RELEASE "${MIDILAR_OUTPUT_DIRECTORY}/bin"
    OUTPUT_NAME "MIDILAR"
    DEBUG_POSTFIX "_d")

set(MIDILAR_BUILD_INCLUDE_DIR
    "${CMAKE_BINARY_DIR}/include/MIDILAR-${PROJECT_VERSION}")

set(MIDILAR_TOP_LEVEL_HEADERS
    "${CMAKE_CURRENT_LIST_DIR}/MIDILAR.h"
    "${CMAKE_CURRENT_LIST_DIR}/MIDILAR_BuildSettings.h")

if(MIDILAR_CORE)
    list(APPEND MIDILAR_TOP_LEVEL_HEADERS
        "${CMAKE_CURRENT_LIST_DIR}/MIDILAR_Core.h")
endif()

target_sources(MIDILAR PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/MIDILAR.cpp"
    ${MIDILAR_TOP_LEVEL_HEADERS})

target_include_directories(MIDILAR
    PUBLIC
        $<BUILD_INTERFACE:${MIDILAR_BUILD_INCLUDE_DIR}>
        $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)

midilar_stage_headers(${MIDILAR_TOP_LEVEL_HEADERS})
midilar_add_dox(
    ${MIDILAR_TOP_LEVEL_HEADERS}
    "${CMAKE_CURRENT_LIST_DIR}/MIDILARTop.dox")

if(MIDILAR_CORE)
    midilar_add_macro(PUBLIC MIDILAR_CORE)
endif()

if(MIDILAR_CORE)
    add_subdirectory(MIDILAR)
endif()

install(TARGETS MIDILAR
    EXPORT MIDILARTargets
    CONFIGURATIONS Release
    ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
    INCLUDES DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}")

install(FILES ${MIDILAR_TOP_LEVEL_HEADERS}
    DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
    CONFIGURATIONS Release)

install(EXPORT MIDILARTargets
    FILE MIDILARTargets.cmake
    NAMESPACE MIDILAR::
    DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/MIDILAR"
    CONFIGURATIONS Release)
