set(MIDILAR_PROTOCOL_HEADERS
    "${CMAKE_CURRENT_LIST_DIR}/Scaling.h"
    "${CMAKE_CURRENT_LIST_DIR}/Channel.h"
    "${CMAKE_CURRENT_LIST_DIR}/Values.h")

target_sources(MIDILAR PRIVATE ${MIDILAR_PROTOCOL_HEADERS})
midilar_stage_headers(${MIDILAR_PROTOCOL_HEADERS})
midilar_add_dox(
    ${MIDILAR_PROTOCOL_HEADERS}
    "${CMAKE_CURRENT_LIST_DIR}/Protocol.dox")

install(FILES ${MIDILAR_PROTOCOL_HEADERS}
    DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/MIDILAR/Protocol"
    CONFIGURATIONS Release)
